name: "Build JDBC deployment container"

on:
  push:
    paths: ["xgjdbc-deploy.dockerfile"]
    branches: [master]
  workflow_dispatch: # Allow manual dispatch

jobs:
  build-push:
    name: "Build and push Docker image"
    runs-on: [self-hosted, build]
    container:
      image: docker:latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Log in to registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push to registry"
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          # Could be using github.repository_owner here, but ghcr is case-picky
          tags: ghcr.io/xeograph/xgjdbc-deploy:latest
