name: "JDBC Deploy"

on:
  push:
    branches: [master]
  workflow_dispatch: # Allow manual dispatch

jobs:
  report:
    name: "Run report"
    runs-on: [self-hosted]
    needs: build-push
    container:
      # Could be using github.repository_owner here, but ghcr is case-picky
      image: ghcr.io/xeograph/xgjdbc-deploy:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Run report script"
        run: python3 deploy.py
        env:
          PYTHONUNBUFFERED: "true"
